apiVersion: batch/v1
kind: CronJob
metadata:
  name: application
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: application
            image: amd64/application:latest
            imagePullPolicy: IfNotPresent
            command: ["/bin/linux/amd64/application"]
          restartPolicy: OnFailure
