apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: application
  labels:
    app: application
    tier: frontend
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: application
        image: amd64/application:latest
