apiVersion: v1
kind: Service
metadata:
  name: application
  labels:
    app: application
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: application
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app: application # has to match .spec.template.metadata.labels
  serviceName: "application"
  replicas: 3 # by default is 1
  minReadySeconds: 10 # by default is 0
  template:
    metadata:
      labels:
        app: application # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: application
        image: amd64/application:latest
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /application
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "storage_class"
      resources:
        requests:
          storage: 1Gi
